'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { getAllData, postApi } from '../../lib/api';
import type { LibraryData, Row } from '../../lib/types';
import { rowTitle } from '../../lib/i18n';

const empty: LibraryData={books:[],chapters:[],videos:[],languages:[],leads:[]};
const uid=(p:string)=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;

export default function AdminPage(){
  const [logged,setLogged]=useState(false); const [password,setPassword]=useState(''); const [loginPassword,setLoginPassword]=useState(''); const [message,setMessage]=useState('');
  const [data,setData]=useState<LibraryData>(empty); const [section,setSection]=useState<'books'|'chapters'|'videos'|'languages'|'leads'>('books'); const [editing,setEditing]=useState<{type:string,item?:Row}|null>(null);
  useEffect(()=>{setLogged(false)},[]);
  async function refresh(){const d=await getAllData(); if(section==='leads'){try{const l=await postApi({action:'getLeads',password}); d.leads=l.data||[]}catch{}} setData(d)}
  async function login(e:FormEvent){e.preventDefault();setMessage('Checking…');try{const r=await postApi({action:'adminLogin',password:loginPassword});if(!r.success)throw new Error();setPassword(loginPassword);setLogged(true);setMessage('');const d=await getAllData();setData(d)}catch{setMessage('Invalid password or connection problem.')}}
  if(!logged) return <main className="login-card"><h1>Admin Login</h1><p className="muted">Enter the password you set in Apps Script.</p><form onSubmit={login}><label>Password<input type="password" required value={loginPassword} onChange={e=>setLoginPassword(e.target.value)}/></label><button className="btn btn-primary full">Login</button><div className="form-message">{message}</div></form></main>;
  return <main className="admin-shell"><div className="admin-grid"><aside className="admin-nav">
    {(['books','chapters','videos','languages','leads'] as const).map(s=><button key={s} className={section===s?'active':''} onClick={async()=>{setSection(s);setEditing(null);if(s==='leads'){try{const d=await getAllData();const l=await postApi({action:'getLeads',password});setData({...d,leads:l.data||[]})}catch{}}else{setData(await getAllData())}}}>{s==='leads'?'Interested Users':s[0].toUpperCase()+s.slice(1)}</button>)}
    <button onClick={()=>{setLogged(false);setPassword('')}}>Logout</button>
  </aside><section className="admin-panel">
    {editing ? <Editor type={editing.type} item={editing.item} data={data} password={password} onCancel={()=>setEditing(null)} onSaved={async()=>{setEditing(null);setData(await getAllData())}}/> : <AdminTable section={section} data={data} onAdd={()=>setEditing({type:section==='leads'?'lead':section.slice(0,-1)})} onEdit={(type,item)=>setEditing({type,item})} onDelete={async(type,id)=>{if(!confirm('Delete this item?'))return;const action={book:'deleteBook',chapter:'deleteChapter',video:'deleteVideo',language:'deleteLanguage'}[type];if(!action)return;const r=await postApi({action,id,password});if(!r.success)alert(r.message||'Delete failed');else setData(await getAllData())}}/>}
  </section></div></main>;
}

function AdminTable({section,data,onAdd,onEdit,onDelete}:{section:string,data:LibraryData,onAdd:()=>void,onEdit:(type:string,item:Row)=>void,onDelete:(type:string,id:string)=>void}){
  if(section==='leads') return <><h1>Interested Users</h1><p className="muted">People who submitted interest from the public website.</p><div className="table-wrap"><table><thead><tr><th>Date</th><th>Book</th><th>Name</th><th>Mobile</th><th>Email</th><th>Language</th></tr></thead><tbody>{(data.leads||[]).map((x,i)=><tr key={i}><td>{x.timestamp}</td><td>{x.bookName}</td><td>{x.name}</td><td>{x.mobile}</td><td>{x.email}</td><td>{x.language}</td></tr>)}</tbody></table></div></>;
  const items=(data as any)[section]||[]; const type=section.slice(0,-1); const heading=section[0].toUpperCase()+section.slice(1);
  return <><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',flexWrap:'wrap'}}><div><h1>{heading}</h1><p className="muted">Create, edit and delete {heading.toLowerCase()}.</p></div><button className="btn btn-primary" onClick={onAdd}>+ Create {type}</button></div><div className="table-wrap"><table><thead><tr>{type==='book'?<><th>Cover</th><th>Telugu</th><th>English</th><th>Active</th><th>Actions</th></>:type==='chapter'?<><th>Book</th><th>No.</th><th>Telugu</th><th>Actions</th></>:type==='video'?<><th>Book</th><th>Chapter</th><th>Title</th><th>Video</th><th>Actions</th></>:<><th>Code</th><th>Name</th><th>Native</th><th>Actions</th></>}</tr></thead><tbody>{items.map((item:Row)=><tr key={String(item.id||item.code)}>{type==='book'?<><td><img src={item.image||'/assets/placeholder-book.svg'} style={{width:45,height:65,objectFit:'cover'}}/></td><td>{item.title_te}</td><td>{item.title_en}</td><td>{String(item.active)}</td><td className="actions"><button className="small-btn" onClick={()=>onEdit('book',item)}>Edit</button><button className="small-btn danger" onClick={()=>onDelete('book',String(item.id))}>Delete</button></td></>:type==='chapter'?<><td>{rowTitle(data.books.find(x=>String(x.id)===String(item.bookId)),'te')}</td><td>{item.chapterNumber}</td><td>{item.title_te}</td><td className="actions"><button className="small-btn" onClick={()=>onEdit('chapter',item)}>Edit</button><button className="small-btn danger" onClick={()=>onDelete('chapter',String(item.id))}>Delete</button></td></>:type==='video'?<><td>{rowTitle(data.books.find(x=>String(x.id)===String(item.bookId)),'te')}</td><td>{data.chapters.find(x=>String(x.id)===String(item.chapterId))?.chapterNumber||''}</td><td>{rowTitle(item,'te')}</td><td><a href={item.videoUrl} target="_blank" rel="noreferrer">Open</a></td><td className="actions"><button className="small-btn" onClick={()=>onEdit('video',item)}>Edit</button><button className="small-btn danger" onClick={()=>onDelete('video',String(item.id))}>Delete</button></td></>:<><td>{item.code}</td><td>{item.name}</td><td>{item.nativeName}</td><td className="actions"><button className="small-btn" onClick={()=>onEdit('language',item)}>Edit</button><button className="small-btn danger" onClick={()=>onDelete('language',String(item.code))}>Delete</button></td></>}</tr>)}</tbody></table></div></>;
}

function Editor({type,item,data,password,onCancel,onSaved}:{type:string,item?:Row,data:LibraryData,password:string,onCancel:()=>void,onSaved:()=>void}){
  const [form,setForm]=useState<Row>(()=>({...item})); const [msg,setMsg]=useState('');
  useEffect(()=>{if(!item){setForm(type==='book'?{id:uid('book'),active:'true'}:type==='chapter'?{id:uid('chapter'),chapterNumber:1,active:'true'}:type==='video'?{id:uid('video'),sortOrder:1,active:'true',language:'te'}:type==='language'?{code:uid('lang'),active:'true'}:{}}):setForm({...item})},[item,type]);
  const set=(k:string,v:any)=>setForm((x)=>({...x,[k]:v}));
  if(type==='lead') return <div><h2>Interested Users</h2><button className="btn btn-soft" onClick={onCancel}>Back</button></div>;
  async function save(e:FormEvent){e.preventDefault();setMsg('Saving…');try{const action=item?`update${type[0].toUpperCase()+type.slice(1)}`:`create${type[0].toUpperCase()+type.slice(1)}`;const r=await postApi({action,id:item?.id||item?.code,data:form,password});if(!r.success)throw new Error(r.message||'Failed');await onSaved()}catch(e:any){setMsg('Could not save: '+e.message)}}
  return <><h2>{item?'Edit':'Create'} {type}</h2><form onSubmit={save}>
    {type==='book'&&<><label>Telugu title<input required value={form.title_te||''} onChange={e=>set('title_te',e.target.value)}/></label><label>English title<input value={form.title_en||''} onChange={e=>set('title_en',e.target.value)}/></label><label>Hindi title<input value={form.title_hi||''} onChange={e=>set('title_hi',e.target.value)}/></label><label>Image URL<input value={form.image||''} onChange={e=>set('image',e.target.value)} placeholder="https://... or assets/filename.jpg"/></label><label>Telugu description<textarea value={form.description_te||''} onChange={e=>set('description_te',e.target.value)}/></label><label>English description<textarea value={form.description_en||''} onChange={e=>set('description_en',e.target.value)}/></label><label>Hindi description<textarea value={form.description_hi||''} onChange={e=>set('description_hi',e.target.value)}/></label></>}
    {type==='chapter'&&<><label>Book<select value={form.bookId||''} onChange={e=>set('bookId',e.target.value)}>{data.books.map(b=><option key={b.id} value={b.id}>{rowTitle(b,'te')}</option>)}</select></label><label>Chapter number<input type="number" value={form.chapterNumber||1} onChange={e=>set('chapterNumber',e.target.value)}/></label><label>Telugu title<input value={form.title_te||''} onChange={e=>set('title_te',e.target.value)}/></label><label>English title<input value={form.title_en||''} onChange={e=>set('title_en',e.target.value)}/></label><label>Hindi title<input value={form.title_hi||''} onChange={e=>set('title_hi',e.target.value)}/></label></>}
    {type==='video'&&<><label>Book<select value={form.bookId||''} onChange={e=>set('bookId',e.target.value)}>{data.books.map(b=><option key={b.id} value={b.id}>{rowTitle(b,'te')}</option>)}</select></label><label>Chapter<select value={form.chapterId||''} onChange={e=>set('chapterId',e.target.value)}>{data.chapters.map(c=><option key={c.id} value={c.id}>{c.chapterNumber} — {rowTitle(c,'te')}</option>)}</select></label><label>Telugu title<input value={form.title_te||''} onChange={e=>set('title_te',e.target.value)}/></label><label>English title<input value={form.title_en||''} onChange={e=>set('title_en',e.target.value)}/></label><label>Hindi title<input value={form.title_hi||''} onChange={e=>set('title_hi',e.target.value)}/></label><label>Video URL<input value={form.videoUrl||''} onChange={e=>set('videoUrl',e.target.value)} placeholder="https://www.youtube.com/watch?v=..."/></label><label>Language<select value={form.language||'te'} onChange={e=>set('language',e.target.value)}><option value="te">Telugu</option><option value="en">English</option><option value="hi">Hindi</option></select></label><label>Sort order<input type="number" value={form.sortOrder||1} onChange={e=>set('sortOrder',e.target.value)}/></label></>}
    {type==='language'&&<><label>Code<input value={form.code||''} onChange={e=>set('code',e.target.value)} placeholder="kn"/></label><label>Name<input value={form.name||''} onChange={e=>set('name',e.target.value)}/></label><label>Native name<input value={form.nativeName||''} onChange={e=>set('nativeName',e.target.value)}/></label></>}
    <label>Active<select value={String(form.active??'true')} onChange={e=>set('active',e.target.value)}><option value="true">Yes</option><option value="false">No</option></select></label>
    <div className="hero-actions"><button className="btn btn-primary">Save</button><button type="button" className="btn btn-soft" onClick={onCancel}>Cancel</button></div><div className="form-message">{msg}</div>
  </form></>;
}
